campaign_user-profile-verify:
    path:     /campaign/user-profile
    defaults: { _controller: BundleUserBundle:Registration:userProfileVerify }
    options:
                expose: true

campaign_user-verify:
    path:     /campaign/user-verify
    defaults: { _controller: BundleUserBundle:Registration:campaignUserVerify }
    options:
                expose: true
campaign_user-confirmation-code:
    path:     /campaign/user-confirmation
    defaults: { _controller: BundleUserBundle:Registration:campaignUserConfirmationCode }
    options:
                expose: true

campaign_user-verified:
    path:     /campaign/user-verified
    defaults: { _controller: BundleUserBundle:Registration:campaignUserVerified }
    options:
                expose: true
user-update:
    path:     /campaign/user-update/{id}
    defaults: { _controller: BundleUserBundle:Registration:userUpdate }

password_changed:
    path:     /campaign/user-password-changed/{id}
    defaults: { _controller: BundleUserBundle:Registration:changePassword }
    requirements:
          id: \d+
