bundle_user_homepage:
    path:     /
    defaults: { _controller: BundleUserBundle:Default:index }

campaign_user-profile-verify:
    path:     /campaign/user-profile
    defaults: { _controller: BundleUserBundle:Registration:userProfileVerify }
    options:
                expose: true

campaign_user-verify:
    path:     /campaign/user-verify
    defaults: { _controller: BundleUserBundle:Registration:campaignUserVerify }
    options:
                expose: true

campaign_user-verified:
    path:     /campaign/user-verified
    defaults: { _controller: BundleUserBundle:Registration:campaignUserVerified }
    options:
                expose: true
