bundle_app_homepage:
    path:     /
    defaults: { _controller: BundleAppBundle:Home:index }

app_bundle_routing_campaign:
    resource: "@BundleAppBundle/Resources/config/routing/campaign.yml"
app_bundle_routing_organization:
    resource: "@BundleAppBundle/Resources/config/routing/organization.yml"