bundle_app_homepage:
    path:     /
    defaults: { _controller: 'BundleAppBundle:Home:index' }

app_bundle_routing_campaign:
    resource: "@BundleAppBundle/Resources/config/routing/campaign.yml"

app_bundle_routing_donation:
    resource: "@BundleAppBundle/Resources/config/routing/donation.yml"

app_bundle_routing_category:
    resource: "@BundleAppBundle/Resources/config/routing/admin/category.yml"

app_bundle_routing_location:
    resource: "@BundleAppBundle/Resources/config/routing/admin/location.yml"

app_bundle_routing_organization:
    resource: "@BundleAppBundle/Resources/config/routing/organization.yml"