Bundle\AppBundle\Entity\Campaign:
    properties:
        title:
            - NotBlank: { message: "Title name should not be blank" }
        amount:
            - NotBlank: { message: "Amount should not be blank" }
            - Regex:
                  pattern: "/^[0-9]+$/i"
                  htmlPattern: "^[0-9]+$"
                  message: "Amount should  be Number"

Bundle\AppBundle\Entity\Organization:
    properties:
        name:
            - NotBlank: { message: "Name  should not be blank" }
#        address:
#            - NotBlank: { message: "Address  should not be blank" }
#        mobileNumber:
#            - NotBlank: { message: "Mobile Number should not be blank" }

Bundle\AppBundle\Entity\Category:
    properties:
        title:
            - NotBlank: { message: "Title  should not be blank" }