security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
               secured_area:
                 logout:       true
                 anonymous:    true
                 form_login:
                     check_path: fos_user_security_check
                     login_path:  fos_user_security_login
                     success_handler: fund.security.authentication_handler
                     failure_handler: fund.security.authentication_handler
                 oauth:
                     resource_owners:
                         facebook:           "/login/check-facebook"
                     login_path:        /login
                     use_forward:       false
                     failure_path:      /login
                     oauth_user_provider:
                         service: app.provider.oauth
               main:
                   pattern: ^/
                   form_login:
                       provider: fos_userbundle
                       check_path: fos_user_security_check
                       csrf_provider: security.csrf.token_manager # Use form.csrf_provider instead for Symfony <2.4

                   logout:       true
                   anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login/check-facebook, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_USER }