campaign_list:
    path:     /campaign
    defaults: { _controller: BundleAppBundle:Campaign:index }

individula_campaign_list:
    path:     /campaign/individula
    defaults: { _controller: BundleAppBundle:Campaign:individualCampaignList }

organizational_campaign_list:
    path:     /campaign/organizational
    defaults: { _controller: BundleAppBundle:Campaign:organizationalCampaignList }

campaign_create:
    path:     /campaign/create
    defaults: { _controller: BundleAppBundle:Campaign:create }

campaign_organization_create:
    path:     /campaign/create-campaign-organization
    defaults: { _controller: BundleAppBundle:Campaign:organizationCampaignCreate }

campaign_individual_create:
    path:     /campaign/individual-create
    defaults: { _controller: BundleAppBundle:Campaign:individualCampaignCreate }

campaign_individual_update:
    path:     /campaign/individual-update/{id}
    defaults: { _controller: BundleAppBundle:Campaign:individualCampaignUpdate }

campaign_detail_create:
    path:     /campaign/detail-create/{id}
    defaults: { _controller: BundleAppBundle:Campaign:campaignDetails }

campaign_detail_update:
    path:     /campaign/detail-update/{id}
    defaults: { _controller: BundleAppBundle:Campaign:campaignDetailsUpdate }

campaign_detail:
    path:     /campaign/detail/{id}
    defaults: { _controller: BundleAppBundle:Campaign:campaignDetails }

campaign_category_based:
    path:     /campaign/category-based/{title}
    defaults: { _controller: BundleAppBundle:Campaign:categoryBasedCampaignList }

campaign_search:
    path:     /campaign/search
    defaults: { _controller: BundleAppBundle:Campaign:campaignSearch }

campaign_search_category_wise:
    path:     /campaign/category-wise-search/{id}
    defaults: { _controller: BundleAppBundle:Campaign:campaignSearchCategoryWise }

campaign_get_image:
    path:     /campaign/image/{id}
    defaults: { _controller: BundleAppBundle:Campaign:getCampaignSingleImage }

campaign_get_progress_bar:
    path:     /campaign/progrress-bar/{id}
    defaults: { _controller: BundleAppBundle:Campaign:getCampaignProgressBar }