campaign_list:
    path:     /campaign
    defaults: { _controller: BundleAppBundle:Campaign:index }

individula_campaign_list:
    path:     /campaign/individula
    defaults: { _controller: BundleAppBundle:Campaign:individualCampaignList }

organizational_campaign_list:
    path:     /campaign/organizational
    defaults: { _controller: BundleAppBundle:Campaign:organizationalCampaignList }

campaign_create:
    path:     /campaign/create
    defaults: { _controller: BundleAppBundle:Campaign:create }

campaign_organization_create:
    path:     /campaign/create-campaign-organization
    defaults: { _controller: BundleAppBundle:Campaign:organizationCampaignCreate }

campaign_individual_create:
    path:     /campaign/individual-create
    defaults: { _controller: BundleAppBundle:Campaign:individualCampaignCreate }


campaign_detail:
    path:     /campaign/detail/{id}
    defaults: { _controller: BundleAppBundle:Campaign:campaignDetails }

campaign_category_based:
    path:     /campaign/category-based/{title}
    defaults: { _controller: BundleAppBundle:Campaign:categoryBasedCampaignList }

campaign_search:
    path:     /campaign/search
    defaults: { _controller: BundleAppBundle:Campaign:campaignSearch }

campaign_search_category_wise:
    path:     /campaign/category-wise-search/{id}
    defaults: { _controller: BundleAppBundle:Campaign:campaignSearchCategoryWise }