<?php

namespace Bundle\AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CampaignRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CampaignRepository extends EntityRepository
{
    public function create($data)
    {
        
        $this->_em->persist($data);
        $this->_em->flush();
        return $data;
    }
    public function getSearchResult($data,$category = null)
    {
        $search = $data['search'];

        $query = $this->createQueryBuilder('cam');
        $query->leftJoin('cam.category', 'c');
        $query->leftJoin('cam.location', 'l');
        $query->where($query->expr()->like("cam.title", "'%$search%'"  ));
        $query->orWhere($query->expr()->like("l.name", "'%$search%'"  ));
        $query->orWhere($query->expr()->like("c.title", "'%$search%'"  ));
        if (!empty($category)){
            $query->andWhere('c.id = :category');
            $query->setParameter('category', $category);
        }
        $query->orderBy('cam.id', 'DESC');
 
        return $query->getQuery()->getResult();
    }
}
