<?php

namespace Bundle\AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CampaignCommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CampaignCommentRepository extends EntityRepository
{
}
