<?php

namespace Bundle\AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CampaignDetailsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CampaignDetailsRepository extends EntityRepository
{
    public function create($data)
    {
        $this->_em->persist($data);
        $this->_em->flush();
        return $data;
    }
}
