<?php

namespace Bundle\AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LocationRepository extends EntityRepository
{
    public function create($data)
    {
        $this->_em->persist($data);
        $this->_em->flush();
        return $data;
    }
    public function persist($data)
    {
        $this->_em->persist($data);
        $this->_em->flush();
        return $data;
    }
}
